# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/setup-node@v3
      
    - name:  Create Customer Env file
      working-directory: ./customer
      run:
         touch .env
         echo APP_SECRET=1234 >> .env
         echo MONGODB_URI=mongodb+srv://paulBarasa:iZn9gxbNyXFusFN0@cluster0.4p1ws.mongodb.net/store-repo?retryWrites=true&w=majority >> .env
         echo MESSAGE_BROKER_URL=amqps://tqjprzjk:Znfz-W94a7nKekimaaQNIYoJFQ4ucT-f@shark.rmq.cloudamqp.com/tqjprzjk >> .env
         echo EXCHANGE_NAME=ONLINE_SHOPPING >> .env
         echo PORT=8001 >> .env
         cat .env
         
    - name: Generate Deploymwent package
      run:
          zip -r deploy.zip . -x '*.git'
          
#     - name: Deploy on Elastic beanstalk QA Env
#       uses: einaregilsson/beanstalk-deploy@v20
#       with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: youtube-ms
#           environment_name: Youtubems-env
#           version_label: "ver-${{ github.sha }}"
#           region: eu-central-1
#           deployment_package: deploy.zip
